services:
  db:
    image: postgres:15
    container_name: mi_postgres
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'publicpass'
      POSTGRES_DB: 'mybookstore'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entryoiunt-initdb.d
    restart: unless-stopped

volumes:
  pgdata: