package com.jessCSerrano.librosLibres.adapters.persistence.repository.author.springdata;

import com.jessCSerrano.librosLibres.adapters.persistence.entity.author.AuthorEntity;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.UUID;

/**
 * Spring Data JPA interface for AuthorEntity persistence.
 * Provides CRUD methods on the authors table.
 * The specific implementation is automatically generated by Spring Data.
 */
public interface SpringDataAuthorRepository extends JpaRepository<AuthorEntity, UUID> {
}
