package com.jessCSerrano.librosLibres.adapters.persistence.repository.book.springdata;

import com.jessCSerrano.librosLibres.adapters.persistence.entity.book.BookEntity;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.UUID;

/**
 * Spring Data JPA interface for BookEntity persistence.
 * Provides CRUD methods on the books table.
 * The specific implementation is automatically generated by Spring Data.
 */
public interface SpringDataBookRepository extends JpaRepository<BookEntity, UUID> {
}
